[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Ozone"
name = "Runtime_Netcode_Patcher"
description = "Patches Netcode RPC methods during runtime utilizing Harmony"
websiteUrl = "https://github.com/NicholasScott1337/RuntimeNetcodeRPCValidator"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../dist/"

[[build.copy]]
source  = "../RuntimeNetcodeRPCValidator/bin/Debug/netstandard2.1/NicholaScott.BepInEx.RuntimeNetcodeRPCValidator.dll"
target = "/NicholaScott.BepInEx.RuntimeNetcodeRPCValidator.dll"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "libraries", "tools"]